sample_name: c_ll_po_0011
fastq_id: 'C6DUUANXX_3_15nf C6DV6ANXX_1_15nf'
fastq_r1: 'C6DUUANXX_3_15nf_1.fastp.fastq.gz C6DV6ANXX_1_15nf_1.fastp.fastq.gz'
fastq_r2: 'C6DUUANXX_3_15nf_2.fastp.fastq.gz C6DV6ANXX_1_15nf_2.fastp.fastq.gz'
in_fastq_folder: /mnt/lustre/hsm/nlsas/notape/home/csic/ebd/jgl/lynx_genome/lynx_data/FASTQ_files/LYNX_09/fastp
reference_genome: /mnt/lustre/hsm/nlsas/notape/home/csic/ebd/jgl/reference_genomes/lynx_lynx_mLynLyn1.2/mLynLyn1.2.revcomp.scaffolds.fa
out_bam_folder: /mnt/lustre/hsm/nlsas/notape/home/csic/ebd/jgl/lynx_genome/lynx_data/mLynLyn1.2_ref_bams
threads: 20
alignment_name: mLynLyn_ref
bwa: bwa
samtools: samtools
picard: 'java -jar /opt/cesga/2020/software/Core/picard/2.25.5/picard.jar'
gatk: 'java -jar /opt/cesga/2020/software/Core/gatk/3.7-0-gcfedb67/GenomeAnalysisTK.jar'