sample_name: c_ll_ba_0230
fastq_id: 'HY5FMDSXX_1_57UDI-idt-UMI HY5FMDSXX_2_57UDI-idt-UMI HY5FMDSXX_3_57UDI-idt-UMI HY5FMDSXX_4_57UDI-idt-UMI HY5WLDSXX_1_57UDI-idt-UMI HY5WLDSXX_2_57UDI-idt-UMI HY5WLDSXX_3_57UDI-idt-UMI HY5WLDSXX_4_57UDI-idt-UMI'
fastq_r1: 'HY5FMDSXX_1_57UDI-idt-UMI_1.fastp.fastq.gz HY5FMDSXX_2_57UDI-idt-UMI_1.fastp.fastq.gz HY5FMDSXX_3_57UDI-idt-UMI_1.fastp.fastq.gz HY5FMDSXX_4_57UDI-idt-UMI_1.fastp.fastq.gz HY5WLDSXX_1_57UDI-idt-UMI_1.fastp.fastq.gz HY5WLDSXX_2_57UDI-idt-UMI_1.fastp.fastq.gz HY5WLDSXX_3_57UDI-idt-UMI_1.fastp.fastq.gz HY5WLDSXX_4_57UDI-idt-UMI_1.fastp.fastq.gz'
fastq_r2: 'HY5FMDSXX_1_57UDI-idt-UMI_2.fastp.fastq.gz HY5FMDSXX_2_57UDI-idt-UMI_2.fastp.fastq.gz HY5FMDSXX_3_57UDI-idt-UMI_2.fastp.fastq.gz HY5FMDSXX_4_57UDI-idt-UMI_2.fastp.fastq.gz HY5WLDSXX_1_57UDI-idt-UMI_2.fastp.fastq.gz HY5WLDSXX_2_57UDI-idt-UMI_2.fastp.fastq.gz HY5WLDSXX_3_57UDI-idt-UMI_2.fastp.fastq.gz HY5WLDSXX_4_57UDI-idt-UMI_2.fastp.fastq.gz'
in_fastq_folder: /mnt/lustre/hsm/nlsas/notape/home/csic/ebd/jgl/lynx_genome/lynx_data/FASTQ_files/LYNX_21/FASTQ/fastp
reference_genome: /mnt/lustre/hsm/nlsas/notape/home/csic/ebd/jgl/reference_genomes/lynx_lynx_mLynLyn1.2/mLynLyn1.2.revcomp.scaffolds.fa
out_bam_folder: /mnt/lustre/hsm/nlsas/notape/home/csic/ebd/jgl/lynx_genome/lynx_data/mLynLyn1.2_ref_bams
threads: 20
alignment_name: mLynLyn_ref
bwa: bwa
samtools: samtools
picard: 'java -jar /opt/cesga/2020/software/Core/picard/2.25.5/picard.jar'
gatk: 'java -jar /opt/cesga/2020/software/Core/gatk/3.7-0-gcfedb67/GenomeAnalysisTK.jar'