sample_name: c_ll_ka_0189
fastq_id: 'CA2W6ANXX_2_5nf CA3D2ANXX_5_5nf'
fastq_r1: 'CA2W6ANXX_2_5nf_1.fastp.fastq.gz CA3D2ANXX_5_5nf_1.fastp.fastq.gz'
fastq_r2: 'CA2W6ANXX_2_5nf_2.fastp.fastq.gz CA3D2ANXX_5_5nf_2.fastp.fastq.gz'
in_fastq_folder: /mnt/lustre/hsm/nlsas/notape/home/csic/ebd/jgl/lynx_genome/lynx_data/FASTQ_files/LYNX_15/LYNX_15/20170206/FASTQ/fastp
reference_genome: /mnt/lustre/hsm/nlsas/notape/home/csic/ebd/jgl/reference_genomes/lynx_lynx_mLynLyn1.2/mLynLyn1.2.revcomp.scaffolds.fa
out_bam_folder: /mnt/lustre/hsm/nlsas/notape/home/csic/ebd/jgl/lynx_genome/lynx_data/mLynLyn1.2_ref_bams
threads: 20
alignment_name: mLynLyn_ref
bwa: bwa
samtools: samtools
picard: 'java -jar /opt/cesga/2020/software/Core/picard/2.25.5/picard.jar'
gatk: 'java -jar /opt/cesga/2020/software/Core/gatk/3.7-0-gcfedb67/GenomeAnalysisTK.jar'